/* XM Arcade — signer abstraction. Amber-compatible.
   Methods: local nsec (device key) ·
   NIP-46 remote signer ("Login with signer" — works with Amber, Nsec.app, etc).
   Amber flow: paste a `bunker://` URI exported from Amber, or generate a
   `nostrconnect://` pairing string and approve it inside Amber. Keys never
   leave the signer; this app only ever sees signatures. */
import { nt, pool, toNpub, parseKeyInput, uid } from "./nostr.js";
import { store } from "./util.js";

const hex = (b) => [...b].map((x) => x.toString(16).padStart(2, "0")).join("");
const hx = (h) => Uint8Array.from(String(h).match(/../g).map((x) => parseInt(x, 16)));
const now = () => Math.floor(Date.now() / 1000);

export function convKey(skBytes, pkHex) {
  return nt.nip44.v2.utils.getConversationKey(skBytes, pkHex);
}
export const nip44Encrypt = (text, ck) => nt.nip44.v2.encrypt(text, ck);
export const nip44Decrypt = (payload, ck) => nt.nip44.v2.decrypt(payload, ck);

const SKEY = "xm.session.v1";
export const Signer = {
  method: null, // 'local' | 'nip46'
  pubkey: null,
  localSk: null, // Uint8Array when method==='local'
  nip46: null,   // {clientSk, clientPk, signerPk, relay, secret}
  _unsub: null,
  _pending: new Map(),
  label: "",
};

function persist() {
  if (Signer.method === "local" && Signer.localSk) {
    store.set(SKEY, { method: "local", sk: hex(Signer.localSk) });
  } else if (Signer.method === "nip46" && Signer.nip46) {
    const n = Signer.nip46;
    store.set(SKEY, { method: "nip46", clientSk: hex(n.clientSk), signerPk: n.signerPk, relay: n.relay, secret: n.secret });
  } else store.del(SKEY);
}
export const isSignedIn = () => !!Signer.method && !!Signer.pubkey;
export const npub = () => (Signer.pubkey ? toNpub(Signer.pubkey) : "");

/* ---------- local device key ---------- */
export function createLocalKey() {
  const sk = nt.generateSecretKey();
  loginLocal(sk);
  return sk;
}
export function loginLocal(skBytes) {
  Signer.localSk = skBytes instanceof Uint8Array ? skBytes : hx(skBytes);
  Signer.pubkey = nt.getPublicKey(Signer.localSk);
  Signer.method = "local";
  Signer.label = "Device key";
  persist();
}
export function loginLocalInput(s) {
  const p = parseKeyInput(s);
  if (!p) throw new Error("That doesn't look like an nsec or 64-char hex key.");
  loginLocal(p.sk);
}

/* ---------- NIP-46 remote signer (Amber & co) ---------- */
export function parseBunkerUri(uri) {
  uri = String(uri || "").trim();
  let pubkey = "", relay = "", secret = "";
  if (uri.startsWith("bunker://")) {
    const u = new URL(uri.replace("bunker://", "https://bunker.invalid/"));
    pubkey = u.pathname.replace(/^\//, "") || u.hostname;
    // bunker://<pubkey>?relay=..&secret=..  → hostname parsing differs; handle both:
    if (u.hostname && u.hostname !== "bunker.invalid") pubkey = u.hostname;
    relay = u.searchParams.get("relay") || "";
    secret = u.searchParams.get("secret") || "";
  } else if (uri.startsWith("nostrconnect://")) {
    // nostrconnect URIs are generated by *us* for pairing; they can't log in.
    throw new Error("nostrconnect:// strings pair a new signer — paste a bunker:// URI to log in.");
  } else throw new Error("Expected a bunker:// URI from your signer app.");
  if (!/^[0-9a-f]{64}$/.test(pubkey)) throw new Error("Bunker URI has a bad signer pubkey.");
  if (!relay.startsWith("wss://")) throw new Error("Bunker URI needs a wss:// relay.");
  return { signerPk: pubkey, relay, secret };
}
export function pairingState(relay = "wss://relay.nsec.app") {
  const clientSk = nt.generateSecretKey();
  const clientPk = nt.getPublicKey(clientSk);
  const secret = hex(nt.generateSecretKey()).slice(0, 32);
  const uri = `nostrconnect://${clientPk}?relay=${encodeURIComponent(relay)}&secret=${secret}&name=${encodeURIComponent("XM Arcade")}&perms=${encodeURIComponent("sign_event:1,4,9,30023,nip44_encrypt,nip44_decrypt")}`;
  return { clientSk, clientPk, relay, secret, uri };
}
function nip46Listen() {
  nip46Close();
  const n = Signer.nip46;
  const ck = convKey(n.clientSk, n.signerPk);
  const sub = pool().subscribeMany([n.relay], [{ kinds: [24133], "#p": [n.clientPk], since: now() - 60 }], {
    onevent(e) {
      try {
        if (e.pubkey !== n.signerPk) return;
        const pt = nip44Decrypt(e.content, ck);
        const msg = JSON.parse(pt);
        const pend = Signer._pending.get(msg.id);
        if (!pend) return;
        Signer._pending.delete(msg.id);
        if (msg.error) pend.reject(new Error(String(msg.error)));
        else pend.resolve(msg.result);
      } catch {}
    },
    oneose() {},
  });
  Signer._unsub = () => { try { sub.close(); } catch {} };
}
function nip46Close() { if (Signer._unsub) { try { Signer._unsub(); } catch {} Signer._unsub = null; } }
async function nip46Request(method, params = []) {
  const n = Signer.nip46;
  if (!n) throw new Error("NIP-46 not connected.");
  const ck = convKey(n.clientSk, n.signerPk);
  const id = uid();
  const content = nip44Encrypt(JSON.stringify({ id, method, params }), ck);
  const tpl = { kind: 24133, created_at: now(), tags: [["p", n.signerPk], ["expiration", String(now() + 120)]], content };
  const signed = nt.finalizeEvent(tpl, n.clientSk);
  const p = new Promise((resolve, reject) => {
    Signer._pending.set(id, { resolve, reject });
    setTimeout(() => { if (Signer._pending.has(id)) { Signer._pending.delete(id); reject(new Error("Signer timed out — approve the request in Amber.")); } }, 60000);
  });
  try { await Promise.all(pool().publish([n.relay], signed)); } catch { throw new Error("Could not reach the signer relay " + n.relay); }
  return p;
}
/* Login with an existing bunker:// URI (Amber → export → paste here). */
export async function loginBunkerUri(uri) {
  const { signerPk, relay, secret } = parseBunkerUri(uri);
  const clientSk = nt.generateSecretKey();
  const clientPk = nt.getPublicKey(clientSk);
  Signer.nip46 = { clientSk, clientPk, signerPk, relay, secret };
  nip46Listen();
  const ack = await nip46Request("connect", [signerPk, secret]);
  if (ack !== "ack") throw new Error("Signer refused the connection.");
  const pk = await nip46Request("get_public_key");
  if (!/^[0-9a-f]{64}$/.test(pk)) throw new Error("Signer returned an invalid public key.");
  Signer.pubkey = pk; Signer.method = "nip46"; Signer.label = "Amber / remote signer";
  persist();
  return pk;
}
/* Pair a fresh signer: show the URI, then wait for the user to approve in Amber. */
export async function pairNewSigner(pair, onWaiting) {
  Signer.nip46 = { clientSk: pair.clientSk, clientPk: pair.clientPk, signerPk: "", relay: pair.relay, secret: pair.secret };
  // We don't know the signer pubkey yet — listen for any 24133 to us.
  nip46Close();
  const sub = pool().subscribeMany([pair.relay], [{ kinds: [24133], "#p": [pair.clientPk], since: now() - 30 }], {
    async onevent(e) {
      try {
        const ck = convKey(pair.clientSk, e.pubkey);
        const pt = nip44Decrypt(e.content, ck);
        const msg = JSON.parse(pt);
        if (msg.result === "ack" || msg.method === "connect") {
          Signer.nip46.signerPk = e.pubkey;
          if (onWaiting) onWaiting("approved");
        }
      } catch {}
    },
    oneose() {},
  });
  Signer._unsub = () => { try { sub.close(); } catch {} };
  if (onWaiting) onWaiting("waiting");
  // Poll for approval until timeout (5 min); the connect ack arrives as a response
  // to our implicit pairing request which Amber answers after scanning the URI.
  const t0 = Date.now();
  while (Date.now() - t0 < 5 * 60 * 1000) {
    await new Promise((r) => setTimeout(r, 1500));
    if (Signer.nip46 && Signer.nip46.signerPk) break;
  }
  if (!Signer.nip46.signerPk) { nip46Close(); throw new Error("Pairing timed out — approve XM Arcade inside Amber and try again."); }
  nip46Listen();
  const pk = await nip46Request("get_public_key");
  Signer.pubkey = pk; Signer.method = "nip46"; Signer.label = "Amber / remote signer";
  persist();
  return pk;
}
/* Android convenience: open Amber directly with an unsigned event (NIP-55). */
export function amberSignUri(unsignedEvent, callbackUrl = "") {
  const payload = encodeURIComponent(JSON.stringify(unsignedEvent));
  let uri = `nostrsigner:${payload}?compressionType=none&returnType=signature&type=SIGN_EVENT`;
  if (callbackUrl) uri += `&callbackUrl=${encodeURIComponent(callbackUrl)}`;
  return uri;
}

/* ---------- unified ops ---------- */
export async function signEvent(tpl) {
  const t = { created_at: now(), kind: tpl.kind, tags: tpl.tags || [], content: tpl.content || "", pubkey: Signer.pubkey };
  if (Signer.method === "local") return nt.finalizeEvent(t, Signer.localSk);
  if (Signer.method === "nip46") {
    const signed = await nip46Request("sign_event", [t]);
    if (!signed || !signed.sig) throw new Error("Remote signer refused to sign.");
    return signed;
  }
  throw new Error("Not signed in.");
}
export async function encryptNip44(peerPk, text) {
  if (Signer.method === "local") return nip44Encrypt(text, convKey(Signer.localSk, peerPk));
  if (Signer.method === "nip46") return nip46Request("nip44_encrypt", [peerPk, text]);
  throw new Error("This signer can't do NIP-44 encryption.");
}
export async function decryptNip44(peerPk, payload) {
  if (Signer.method === "local") return nip44Decrypt(payload, convKey(Signer.localSk, peerPk));
  if (Signer.method === "nip46") return nip46Request("nip44_decrypt", [peerPk, payload]);
  throw new Error("This signer can't do NIP-44 decryption.");
}
export function logout() {
  nip46Close();
  Signer.method = null; Signer.pubkey = null; Signer.localSk = null; Signer.nip46 = null;
  Signer._pending.clear(); Signer.label = "";
  persist();
}
/* Restore a previous session (local key or bunker). */
export async function restoreSession() {
  const s = store.get(SKEY, null);
  if (!s) return false;
  try {
    if (s.method === "local" && s.sk) { loginLocal(hx(s.sk)); return true; }
    if (s.method === "nip46" && s.clientSk && s.signerPk) {
      Signer.nip46 = { clientSk: hx(s.clientSk), clientPk: nt.getPublicKey(hx(s.clientSk)), signerPk: s.signerPk, relay: s.relay, secret: s.secret };
      nip46Listen();
      try {
        const pk = await Promise.race([nip46Request("get_public_key"), new Promise((_, rej) => setTimeout(() => rej(new Error("timeout")), 12000))]);
        Signer.pubkey = pk; Signer.method = "nip46"; Signer.label = "Amber / remote signer";
        return true;
      } catch { nip46Close(); Signer.nip46 = null; return false; }
    }
  } catch {}
  return false;
}
